### PR TITLE
Ignore data resource

### LINKED ISSUE #49: Handle inline data
Should not error on inline data. I have a branch that fixes this. I'll create a PR as soon as I submit this.

## Reproduce
`dpm install https://github.com/waylonflinn/datapackage-example-inline`

https://github.com/waylonflinn/datapackage-example-inline

### PR DESCRIPTION
**Pull request by waylonflinn**
Allows downloading packages with inline data resources.

fixes #49

### CODE REVIEW

**Comment by rgrp** [comment]
@waylonflinn thanks for this - patch looks good and a nice proper test (though it would be good to move that example package perhaps into the test directory in this repo so we do not have breakage later if you move stuff).

I'm going to merge this now but request that you then add a minimal datapackage example into the fixtures directory https://github.com/okfn/dpm/tree/master/test/fixtures and update the test to use it.

**Comment by waylonflinn** [comment]
Thanks, I was concerned about that as well. It wasn't clear to me how to get the test to use local data. I'm sure I'm just overlooking the relevant example. Suggestions or pointers appreciated.

**Comment by rgrp** [comment]
@waylonflinn for `get` command testing with local will be tough. So suggest here was still to use a remote url but use one that we have committed into the test/fixtures directory of this package. does that make sense?

**Comment by waylonflinn** [comment]
now I get it. thanks for clarifying. will put a PR together tomorrow.

**Pull request merged**
